### ISSUE TITLE
Authentication issue. 

### ISSUE THREAD

**Issue by ryanharper** [emccode/goair#1]
Gents nice code....!! 

I am trying to get this to run on Vcloud director and get the following error. 

2015/04/02 20:46:46 failed authenticating: error Authenticating: error processing backend url action: API Error: 406: The request has invalid accept header. Supported API versions are: [1.5, 5.1, 5.5]

I was wondering if you could clarify the below in your documentation.
"Additionally you can use it in an indepdenent mode to connect directly to vCloud Director instances."
Does this work with vcoud director, i.e onsite installations?  If so is there an env Variable or something I may be missing when initialising the cli

any clarification on this would be greatly appreciated. 

Cheers
Ryan

**Comment by clintonskitson** [comment]
Ryan, thanks for the feedback! From the looks of it you are running a vCloud Director instance that is 5.5.  The govcloudair package is written for 5.6+.  You could modify the code and replace 5.6 with 5.5 on the HTTP header portions and recompile.  I can't say it will work as designed however since types, etc were built for 5.6.

**Comment by clintonskitson** [comment]
And yes, the independent mode allows you to use goair against local vCloud instances.

**Comment by ryanharper** [comment]
thanks for coming back to me, I have had a little dig about the code, and looks like there are some major differences in the 5.5 code to 5.6, I will push for ops to get us updated to 5.6.
